const musicData = {
  altRock: [
    {
      name: 'Shut up The Adults are Talking - The Strokes',
      art: 'Song-Covers/Alt-Rock/adults-talking.jpeg',
      sample: 'Song-Samples/Alt-Rock/adults-talking.mp3',
      pop: 1,
      jazz: 0,
      classicRock: 2,
      rap: 0,
      indie: 3,
      rnb: 0,
      metal: 1,
      blues: 0,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 1,
      altRock: 5,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Goodie Bag - Still Woozy',
      art: 'Song-Covers/Alt-Rock/goodie-bag.jpeg',
      sample: 'Song-Samples/Alt-Rock/Goodie Bag.mp3',
      pop: 1,
      jazz: 2,
      classicRock: 0,
      rap: 1,
      indie: 4,
      rnb: 1,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 5,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Everlong - Foo Fighters',
      art: 'Song-Covers/Alt-Rock/everlong.jpeg',
      sample: 'Song-Samples/Alt-Rock/Everlong.mp3',
      pop: 0,
      jazz: 0,
      classicRock: 4,
      rap: 0,
      indie: 3,
      rnb: 1,
      metal: 1,
      blues: 0,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 5,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'The Less I Know the Better - Tame Impala',
      art: 'Song-Covers/Alt-Rock/tame-impala.jpeg',
      sample: 'Song-Samples/Alt-Rock/Tame Impala - The Less I Know The Better (Audio).mp3',
      pop: 0,
      jazz: 1,
      classicRock: 2,
      rap: 0,
      indie: 4,
      rnb: 1,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 3,
      altRock: 5,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    genre = 'altRock',
  ],

  blues: [
    {
      name: 'Id Rather Go Blind - Etta James',
      art: 'Song-Covers/Blues/go-blind.jpeg',
      sample: 'Song-Samples/Blues/rather-go-blind.mp3',
      pop: 0,
      jazz: 2,
      classicRock: 0,
      rap: 0,
      indie: 0,
      rnb: 0,
      metal: 0,
      blues: 3,
      folk: 0,
      soul: 5,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 1,
      score: 0,
    },
    {
      name: 'Aint No Love in the Heart of the City - Bobby Bland',
      art: 'Song-Covers/Blues/aint-no-love.jpg',
      sample: 'Song-Samples/Blues/no-love.mp3',
      pop: 0,
      jazz: 2,
      classicRock: 1,
      rap: 0,
      indie: 0,
      rnb: 0,
      metal: 0,
      blues: 5,
      folk: 0,
      soul: 4,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 1,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Boom Boom - John Lee Hooker',
      art: 'Song-Covers/Blues/boomboom.webp',
      sample: 'Song-Samples/Blues/John Lee Hooker - Boom Boom.mp3',
      pop: 0,
      jazz: 2,
      classicRock: 0,
      rap: 0,
      indie: 0,
      rnb: 1,
      metal: 0,
      blues: 5,
      folk: 0,
      soul: 3,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 1,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Chains and Things - BB King',
      art: 'Song-Covers/Blues/chains-and-things.jpeg',
      sample: 'Song-Samples/Blues/Chains And Things.mp3',
      pop: 0,
      jazz: 3,
      classicRock: 0,
      rap: 0,
      indie: 0,
      rnb: 1,
      metal: 0,
      blues: 5,
      folk: 0,
      soul: 2,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 2,
      altRock: 1,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    genre = 'blues',
  ],

  classicRock: [
    {
      name: 'American Girl - Tom Petty',
      art: 'Song-Covers/Classic-Rock/american-girl.jpeg',
      sample: 'Song-Samples/Classic-Rock/american-girl.mp3',
      pop: 1,
      jazz: 0,
      classicRock: 5,
      rap: 0,
      indie: 1,
      rnb: 0,
      metal: 1,
      blues: 1,
      folk: 0,
      soul: 0,
      country: 1,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 1,
      altRock: 2,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Killer Queen - Queen',
      art: 'Song-Covers/Classic-Rock/killer-queen.jpeg',
      sample: 'Song-Samples/Classic-Rock/Killer Queen (Remastered 2011).mp3',
      pop: 0,
      jazz: 0,
      classicRock: 5,
      rap: 0,
      indie: 1,
      rnb: 1,
      metal: 0,
      blues: 1,
      folk: 0,
      soul: 1,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 1,
      altRock: 3,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Long Cool Woman in a Black Dress - The Hollies',
      art: 'Song-Covers/Classic-Rock/Long_Cool_Woman_in_a_Black_Dress.jpg',
      sample: 'Song-Samples/Classic-Rock/The Hollies - Long Cool Woman (In a Black Dress) (Official Audio).mp3',
      pop: 0,
      jazz: 0,
      classicRock: 5,
      rap: 0,
      indie: 1,
      rnb: 1,
      metal: 0,
      blues: 0,
      folk: 1,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 2,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Start Me Up - The Rolling Stones',
      art: 'Song-Covers/Classic-Rock/start-me-up.jpeg',
      sample: 'Song-Samples/Classic-Rock/The Rolling Stones - Start Me Up - Official Promo (1).mp3',
      pop: 0,
      jazz: 0,
      classicRock: 5,
      rap: 0,
      indie: 1,
      rnb: 1,
      metal: 1,
      blues: 1,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 3,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    genre = 'classicRock',
  ],
  
  classical: [
    {
      name: 'Lacrimosa - Mozart',
      art: 'Song-Covers/Classical/lacrimosa.jpeg',
      sample: 'Song-Samples/Classical/lacrimosa.mp3',
      pop: 0,
      jazz: 0,
      classicRock: 0,
      rap: 0,
      indie: 0,
      rnb: 0,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 5,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Piano Sonata No. 2 in B flat Minor',
      art: 'Song-Covers/Classical/chopin.jpeg',
      sample: 'Song-Samples/Classical/Piano Sonata No. 2 in B flat Minor.mp3',
      pop: 0,
      jazz: 0,
      classicRock: 0,
      rap: 0,
      indie: 0,
      rnb: 0,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 5,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Howls Moving Castle Theme',
      art: 'Song-Covers/Classical/howl.jpeg',
      sample: 'Song-Samples/Classical/howls.mp3',
      pop: 0,
      jazz: 1,
      classicRock: 0,
      rap: 0,
      indie: 0,
      rnb: 0,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 5,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Moonlight Sonata - Beethoven',
      art: 'Song-Covers/Classical/sonata-14.jpeg',
      sample: 'Song-Samples/Classical/Beethoven - Moonlight Sonata (Piano Sonata No. 14, Op. 27 No. 2, 1st Movement).mp3',
      pop: 0,
      jazz: 0,
      classicRock: 0,
      rap: 0,
      indie: 0,
      rnb: 0,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 5,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    genre = 'classical',
  ],
  
  country: [
    {
      name: 'Written in the Sand - Old Dominion',
      art: 'Song-Covers/Country/written-in-the-sand.jpeg',
      sample: 'Song-Samples/Country/written-in-sand.mp3',
      pop: 3,
      jazz: 0,
      classicRock: 0,
      rap: 0,
      indie: 1,
      rnb: 0,
      metal: 0,
      blues: 0,
      folk: 2,
      soul: 0,
      country: 5,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Cover Me Up - Jason Isabelle',
      art: 'Song-Covers/Country/covermeup.jpeg',
      sample: 'Song-Samples/Country/Cover Me Up.mp3',
      pop: 0,
      jazz: 0,
      classicRock: 0,
      rap: 0,
      indie: 2,
      rnb: 1,
      metal: 0,
      blues: 1,
      folk: 3,
      soul: 0,
      country: 5,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'I Choose You - The Steeldrivers',
      art: 'Song-Covers/Country/steeldrivers.jpg',
      sample: 'Song-Samples/Country/The SteelDrivers  I Choose You (Official Lyric Video).mp3',
      pop: 0,
      jazz: 0,
      classicRock: 1,
      rap: 0,
      indie: 2,
      rnb: 0,
      metal: 0,
      blues: 1,
      folk: 3,
      soul: 1,
      country: 5,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Parachute - Chris Stapleton',
      art: 'Song-Covers/Country/traveller.jpeg',
      sample: 'Song-Samples/Country/Parachute.mp3',
      pop: 0,
      jazz: 0,
      classicRock: 0,
      rap: 0,
      indie: 1,
      rnb: 0,
      metal: 0,
      blues: 2,
      folk: 2,
      soul: 0,
      country: 5,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    genre = 'country',
  ],
  
  folk: [
    {
      name: 'In Dreams - Sierra Ferrel',
      art: 'Song-Covers/Folk/in-dreams.jpeg',
      sample: 'Song-Samples/Folk/in-dreams.mp3',
      pop: 0,
      jazz: 1,
      classicRock: 0,
      rap: 0,
      indie: 4,
      rnb: 0,
      metal: 0,
      blues: 0,
      folk: 5,
      soul: 2,
      country: 4,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Charleston Girl - Tyler Childers',
      art: 'Song-Covers/Folk/charletson-girl.jpeg',
      sample: 'Song-Samples/Folk/Charleston Girl (Live).mp3',
      pop: 0,
      jazz: 1,
      classicRock: 0,
      rap: 0,
      indie: 2,
      rnb: 0,
      metal: 0,
      blues: 0,
      folk: 5,
      soul: 0,
      country: 4,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Montreal - Ghost of Paul Revere',
      art: 'Song-Covers/Folk/montreal.jpeg',
      sample: 'Song-Samples/Folk/Ghost of Paul Revere - _Montreal_ (Official Audio).mp3',
      pop: 0,
      jazz: 1,
      classicRock: 0,
      rap: 0,
      indie: 0,
      rnb: 0,
      metal: 0,
      blues: 2,
      folk: 5,
      soul: 1,
      country: 4,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Wondering Why - Red Clay',
      art: 'Song-Covers/Folk/wondering-why.jpeg',
      sample: 'Song-Samples/Folk/Wondering Why.mp3',
      pop: 0,
      jazz: 0,
      classicRock: 0,
      rap: 0,
      indie: 3,
      rnb: 0,
      metal: 0,
      blues: 0,
      folk: 5,
      soul: 0,
      country: 4,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    genre = 'folk',
  ],
  
  funk: [
    {
      name: 'Dr. Funk - The Main Squeeze',
      art: 'Song-Covers/Funk/the-main-squeeze.jpg',
      sample: 'Song-Samples/Funk/dr-funk.mp3',
      pop: 0,
      jazz: 3,
      classicRock: 0,
      rap: 0,
      indie: 1,
      rnb: 0,
      metal: 0,
      blues: 1,
      folk: 0,
      soul: 1,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 5,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Watermelon Man - Herbie Hancock',
      art: 'Song-Covers/Funk/watermelon-man.jpeg',
      sample: 'Song-Samples/Funk/Watermelon Man.mp3',
      pop: 0,
      jazz: 4,
      classicRock: 0,
      rap: 0,
      indie: 0,
      rnb: 2,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 5,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 1,
      score: 0,
    },
    {
      name: 'Can You Get To That - Funkadelics',
      art: 'Song-Covers/Funk/canyougettothat.jpg',
      sample: 'Song-Samples/Funk/Funkadelic - Can You Get To That (HQ).mp3',
      pop: 0,
      jazz: 2,
      classicRock: 0,
      rap: 0,
      indie: 1,
      rnb: 1,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 3,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 5,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Them Changes - Thundercat',
      art: 'Song-Covers/Funk/them-changes.jpeg',
      sample: 'Song-Samples/Funk/themchanges.mp3',
      pop: 0,
      jazz: 3,
      classicRock: 0,
      rap: 0,
      indie: 2,
      rnb: 0,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 5,
      altRock: 2,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    genre = 'funk',
  ],
  
  house: [
    {
      name: 'Dancin - Krono Remix',
      art: 'Song-Covers/House/dancin.jpeg',
      sample: 'Song-Samples/House/dancin.mp3',
      pop: 3,
      jazz: 0,
      classicRock: 0,
      rap: 0,
      indie: 0,
      rnb: 1,
      metal: 0,
      blues: 1,
      folk: 0,
      soul: 1,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 5,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Afraid to Feel - LF System',
      art: 'Song-Covers/House/afraid-to-feel.png',
      sample: 'Song-Samples/House/LF SYSTEM - Afraid To Feel (Official Lyric Video).mp3',
      pop: 3,
      jazz: 0,
      classicRock: 0,
      rap: 0,
      indie: 0,
      rnb: 2,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 1,
      altRock: 0,
      trap: 0,
      house : 5,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Baby Girl - Disco Lines',
      art: 'Song-Covers/House/baby-girl.jpeg',
      sample: 'Song-Samples/House/Disco Lines - Baby Girl (Official Video).mp3',
      pop: 1,
      jazz: 0,
      classicRock: 0,
      rap: 0,
      indie: 1,
      rnb: 0,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 2,
      altRock: 0,
      trap: 2,
      house : 5,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Plasma - DR. GABBA',
      art: 'Song-Covers/House/plasma.jpeg',
      sample: 'Song-Samples/House/Plasma.mp3',
      pop: 1,
      jazz: 0,
      classicRock: 0,
      rap: 0,
      indie: 0,
      rnb: 0,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 3,
      altRock: 0,
      trap: 1,
      house : 5,
      neoSoul: 0,
      score: 0,
    },
    genre = 'house',
  ],
  
  indie: [
    {
      name: 'Kilby Girl - Backseat Lovers',
      art: 'Song-Covers/Indie/kilby-girl.jpeg',
      sample: 'Song-Samples/Indie/kilby-girl.mp3',
      pop: 2,
      jazz: 0,
      classicRock: 0,
      rap: 0,
      indie: 5,
      rnb: 0,
      metal: 0,
      blues: 0,
      folk: 1,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 3,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Float - HARBOUR',
      art: 'Song-Covers/Indie/float.jpeg',
      sample: 'Song-Samples/Indie/HARBOUR - Float.mp3',
      pop: 2,
      jazz: 1,
      classicRock: 0,
      rap: 0,
      indie: 5,
      rnb: 0,
      metal: 0,
      blues: 0,
      folk: 1,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 2,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Show me Naomi - Bahama',
      art: 'Song-Covers/Indie/show-me-naomi.jpeg',
      sample: 'Song-Samples/Indie/Show Me Naomi.mp3',
      pop: 1,
      jazz: 1,
      classicRock: 0,
      rap: 0,
      indie: 5,
      rnb: 0,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 1,
      altRock: 1,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Silhouettes - Colony House',
      art: 'Song-Covers/Indie/silhouttes.jpeg',
      sample: 'Song-Samples/Indie/Silhouettes.mp3',
      pop: 0,
      jazz: 0,
      classicRock: 1,
      rap: 0,
      indie: 5,
      rnb: 0,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 2,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 2,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    genre = 'indie',
  ],
  
  jazz: [
    {
      name: 'Strausburg St. Denis - Roy Hargrave',
      art: 'Song-Covers/Jazz/strausburg.jpeg',
      sample: 'Song-Samples/Jazz/strausburg.mp3',
      pop: 0,
      jazz: 5,
      classicRock: 0,
      rap: 0,
      indie: 0,
      rnb: 0,
      metal: 0,
      blues: 2,
      folk: 0,
      soul: 2,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'In a Sentimental Mood - Duke Ellington & John Coltrane',
      art: 'Song-Covers/Jazz/in-a-sentimental-mood.jpeg',
      sample: 'Song-Samples/Jazz/Duke Ellington & John Coltrane - In a sentimental mood.mp3',
      pop: 0,
      jazz: 5,
      classicRock: 0,
      rap: 0,
      indie: 0,
      rnb: 0,
      metal: 0,
      blues: 1,
      folk: 0,
      soul: 1,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Take Five - Dave Brubeck',
      art: 'Song-Covers/Jazz/take-five.jpeg',
      sample: 'Song-Samples/Jazz/Dave Brubeck - Take Five.mp3',
      pop: 0,
      jazz: 5,
      classicRock: 0,
      rap: 0,
      indie: 0,
      rnb: 0,
      metal: 0,
      blues: 1,
      folk: 0,
      soul: 1,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Mercy, Mercy, Mercy - Cannonball Adderley',
      art: 'Song-Covers/Jazz/Mercymercymercy.jpg',
      sample: 'Song-Samples/Jazz/onlymp3.to - Cannonball Adderley Quintet Mercy Mercy Mercy 1966 -s4rXEKtC8iY-192k-1704499549.mp3',
      pop: 0,
      jazz: 5,
      classicRock: 0,
      rap: 0,
      indie: 0,
      rnb: 0,
      metal: 0,
      blues: 1,
      folk: 0,
      soul: 1,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    genre = 'jazz',
  ],
  
  metal: [
    {
      name: 'Crazy Train - Ozzy Ozborn',
      art: 'Song-Covers/Metal/crazy-train.jpeg',
      sample: 'Song-Samples/Metal/crazy-train.mp3',
      pop: 0,
      jazz: 0,
      classicRock: 4,
      rap: 0,
      indie: 0,
      rnb: 0,
      metal: 5,
      blues: 0,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 3,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Lamb of God - Evidence',
      art: 'Song-Covers/Metal/evidence.webp',
      sample: 'Song-Samples/Metal/Lamb of God - Evidence (Official Lyric Video).mp3',
      pop: 0,
      jazz: 0,
      classicRock: 2,
      rap: 0,
      indie: 0,
      rnb: 0,
      metal: 5,
      blues: 0,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 1,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'The Summoning - Sleep Token',
      art: 'Song-Covers/Metal/the-summoning.jpeg',
      sample: 'Song-Samples/Metal/Sleep Token - The Summoning.mp3',
      pop: 0,
      jazz: 0,
      classicRock: 2,
      rap: 0,
      indie: 0,
      rnb: 0,
      metal: 5,
      blues: 0,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 1,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Too Far Gone - Metallica',
      art: 'Song-Covers/Metal/too-far-gone.jpeg',
      sample: 'Song-Samples/Metal/Metallica_ Too Far Gone_ (Official Music Video).mp3',
      pop: 0,
      jazz: 0,
      classicRock: 2,
      rap: 0,
      indie: 0,
      rnb: 0,
      metal: 5,
      blues: 0,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 1,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    genre = 'metal',
  ],
  
  neoSoul: [
    {
      name: 'Cant Take My Eyes off You - Lauryn Hill',
      art: 'Song-Covers/Neo-Soul/eyes-off-you.jpeg',
      sample: 'Song-Samples/Neo-Soul/eyes-off-you.mp3',
      pop: 0,
      jazz: 2,
      classicRock: 0,
      rap: 2,
      indie: 0,
      rnb: 4,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 3,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 5,
      score: 0,
    },
    {
      name: 'Brown Sugar - DAngelo',
      art: 'Song-Covers/Neo-Soul/brown-sugar.jpeg',
      sample: 'Song-Samples/Neo-Soul/Brown Sugar.mp3',
      pop: 1,
      jazz: 3,
      classicRock: 0,
      rap: 3,
      indie: 0,
      rnb: 3,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 2,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 2,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 5,
      score: 0,
    },
    {
      name: 'Didnt Cha Know',
      art: 'Song-Covers/Neo-Soul/didnt-cha-know.jpeg',
      sample: 'Song-Samples/Neo-Soul/didnt-cha-know.mp3',
      pop: 1,
      jazz: 2,
      classicRock: 0,
      rap: 2,
      indie: 1,
      rnb: 4,
      metal: 0,
      blues: 1,
      folk: 0,
      soul: 3,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 1,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 5,
      score: 0,
    },
    {
      name: 'You Dont Know my Name',
      art: 'Song-Covers/Neo-Soul/you-dont-know-my-name.jpeg',
      sample: 'Song-Samples/Neo-Soul/know-my-name.mp3',
      pop: 1,
      jazz: 1,
      classicRock: 0,
      rap: 2,
      indie: 1,
      rnb: 3,
      metal: 0,
      blues: 1,
      folk: 0,
      soul: 2,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 5,
      score: 0,
    },
    genre = 'neoSoul',
  ],
  
  pop: [
    {
      name: '7 Years - Lucas Graham',
      art: 'Song-Covers/Pop/seven-years.jpeg',
      sample: 'Song-Samples/Pop/seven-years.mp3',
      pop: 5,
      jazz: 0,
      classicRock: 0,
      rap: 0,
      indie: 1,
      rnb: 0,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 1,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Let Her Go - Passenger',
      art: 'Song-Covers/Pop/ab67616d0000b273a7c10595167c713a2df0f187.jpeg',
      sample: 'Song-Samples/Pop/Passenger  Let Her Go (Official Video).mp3',
      pop: 5,
      jazz: 1,
      classicRock: 0,
      rap: 0,
      indie: 2,
      rnb: 0,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 2,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 1,
      score: 0,
    },
    {
      name: 'I Gotta Feeling - Black Eyed Peas',
      art: 'Song-Covers/Pop/i-gotta-feeling.webp',
      sample: 'Song-Samples/Pop/I Gotta Feeling.mp3',
      pop: 5,
      jazz: 0,
      classicRock: 0,
      rap: 3,
      indie: 0,
      rnb: 2,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 1,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 1,
      trap: 0,
      house : 0,
      neoSoul: 1,
      score: 0,
    },
    {
      name: 'Whatcha Say - Jason Derulo',
      art: 'Song-Covers/Pop/whatcha-say.jpeg',
      sample: 'Song-Samples/Pop/Jason Derulo - Whatcha Say [Official Music Video].mp3',
      pop: 5,
      jazz: 0,
      classicRock: 0,
      rap: 0,
      indie: 0,
      rnb: 3,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 1,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 2,
      score: 0,
    },
    genre = 'pop',
  ],
  
  rnb: [
    {
      name: 'Leave the Door Open - Silk Sonic',
      art: 'Song-Covers/R&B/silk-sonic-cover.png',
      sample: 'Song-Samples/R&B/silk-sonic-sample.mp3',
      pop: 2,
      jazz: 2,
      classicRock: 0,
      rap: 0,
      indie: 0,
      rnb: 5,
      metal: 0,
      blues: 1,
      folk: 0,
      soul: 1,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 3,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 2,
      score: 0,
    },
    {
      name: 'Garden Kisses - Giveon',
      art: 'Song-Covers/R&B/garden-kises.jpeg',
      sample: 'Song-Samples/R&B/Garden Kisses.mp3',
      pop: 2,
      jazz: 0,
      classicRock: 0,
      rap: 1,
      indie: 0,
      rnb: 5,
      metal: 0,
      blues: 1,
      folk: 0,
      soul: 1,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 2,
      score: 0,
    },
    {
      name: 'Lost - Frank Ocean',
      art: 'Song-Covers/R&B/lost.jpeg',
      sample: 'Song-Samples/R&B/Lost.mp3',
      pop: 2,
      jazz: 1,
      classicRock: 0,
      rap: 0,
      indie: 2,
      rnb: 5,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 1,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Poison - Brent Faiyez',
      art: 'Song-Covers/R&B/poison.jpeg',
      sample: 'Song-Samples/R&B/Poison (1).mp3',
      pop: 2,
      jazz: 0,
      classicRock: 0,
      rap: 2,
      indie: 0,
      rnb: 5,
      metal: 0,
      blues: 1,
      folk: 0,
      soul: 1,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    genre = 'rnb',
  ],
  
  rap: [
    {
      name: 'The Ends - Travis Scott',
      art: 'Song-Covers/Rap/the-ends-cover.png',
      sample: 'Song-Samples/Rap/the-ends.mp3',
      pop: 0,
      jazz: 1,
      classicRock: 0,
      rap: 5,
      indie: 0,
      rnb: 1,
      metal: 0,
      blues: 1,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 4,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Look Over Your Shoulder - Busta Rhymes',
      art: 'Song-Covers/Rap/look-over-your-shoulder.jpg',
      sample: 'Song-Samples/Rap/Busta Rhymes - Look Over Your Shoulder (Visualizer) ft. Kendrick Lamar.mp3',
      pop: 0,
      jazz: 2,
      classicRock: 0,
      rap: 5,
      indie: 0,
      rnb: 0,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 1,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Headshots - Isaiah Rashad',
      art: 'Song-Covers/Rap/headshots.jpeg',
      sample: 'Song-Samples/Rap/Isaiah Rashad - Headshots (4r da locals) Visualizer.mp3',
      pop: 0,
      jazz: 2,
      classicRock: 0,
      rap: 5,
      indie: 0,
      rnb: 3,
      metal: 0,
      blues: 1,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Surround Sound - JID',
      art: 'Song-Covers/Rap/surround-sound.jpeg',
      sample: 'Song-Samples/Rap/Surround Sound.mp3',
      pop: 1,
      jazz: 2,
      classicRock: 0,
      rap: 5,
      indie: 0,
      rnb: 2,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 2,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 2,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    genre = 'rap',
  ],
  
  reggae: [
    {
      name: 'Could You Be Loved - Bob Marley',
      art: 'Song-Covers/Reggae/could-you-be-loved.jpeg',
      sample: 'Song-Samples/Reggae/could-you-be-loved.mp3',
      pop: 0,
      jazz: 3,
      classicRock: 0,
      rap: 0,
      indie: 2,
      rnb: 1,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 5,
      funk: 1,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Three Little Birds - Bob Marley & The Wailers',
      art: 'Song-Covers/Reggae/birds.jpeg',
      sample: 'Song-Samples/Reggae/Bob Marley & The Wailers - Three Little Birds (Official Video).mp3',
      pop: 0,
      jazz: 0,
      classicRock: 0,
      rap: 0,
      indie: 1,
      rnb: 0,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 5,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Fighting Against Conviction - Bunny Wailer',
      art: 'Song-Covers/Reggae/conviction.webp',
      sample: 'Song-Samples/Reggae/Bunny Wailer - Fighting Against Conviction.mp3',
      pop: 0,
      jazz: 0,
      classicRock: 0,
      rap: 0,
      indie: 1,
      rnb: 0,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 5,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Dont Give Up - Barrington Levy',
      art: 'Song-Covers/Reggae/dontgiveup.jpeg',
      sample: 'Song-Samples/Reggae/dont-give-up.mp3',
      pop: 0,
      jazz: 0,
      classicRock: 0,
      rap: 0,
      indie: 1,
      rnb: 0,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 5,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    genre = 'reggae',
  ],
  
  soul: [
    {
      name: 'At Last - Etta James',
      art: 'Song-Covers/Soul/at-last.webp',
      sample: 'Song-Samples/Soul/at-last.mp3',
      pop: 0,
      jazz: 2,
      classicRock: 0,
      rap: 0,
      indie: 1,
      rnb: 2,
      metal: 0,
      blues: 2,
      folk: 0,
      soul: 5,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 2,
      score: 0,
    },
    {
      name: 'If you Dont Know Me by Now - Harold Melvin and the Blue Notes',
      art: 'Song-Covers/Soul/harold-melvin.jpg',
      sample: 'Song-Samples/Soul/know-me-by-now.mp3',
      pop: 0,
      jazz: 2,
      classicRock: 0,
      rap: 0,
      indie: 0,
      rnb: 2,
      metal: 0,
      blues: 2,
      folk: 0,
      soul: 5,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'I Feel a Change - Charles Bradley',
      art: 'Song-Covers/Soul/i-feel-a-change.jpeg',
      sample: 'Song-Samples/Soul/I Feel a Change (1).mp3',
      pop: 0,
      jazz: 1,
      classicRock: 0,
      rap: 0,
      indie: 0,
      rnb: 0,
      metal: 0,
      blues: 2,
      folk: 0,
      soul: 5,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Lets Stay Together - Al Green',
      art: 'Song-Covers/Soul/Letsstaytogether.jpeg',
      sample: 'Song-Samples/Soul/stay-together.mp3',
      pop: 0,
      jazz: 1,
      classicRock: 0,
      rap: 0,
      indie: 0,
      rnb: 0,
      metal: 0,
      blues: 2,
      folk: 0,
      soul: 5,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 0,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    genre = 'soul',
  ],
  
  trap: [
    {
      name: 'Raindrops - Metro Boomin',
      art: 'Song-Covers/Trap/raindrops.jpeg',
      sample: 'Song-Samples/Trap/raindrops.mp3',
      pop: 0,
      jazz: 0,
      classicRock: 0,
      rap: 4,
      indie: 0,
      rnb: 1,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 5,
      house : 0,
      neoSoul: 1,
      score: 0,
    },
    {
      name: 'Ronda (Winners) - Lil Uzi Vert',
      art: 'Song-Covers/Trap/ronda.jpeg',
      sample: 'Song-Samples/Trap/Lil Uzi Vert - Ronda (Winners) [Produced By Metro Boomin  CuBeatz].mp3',
      pop: 0,
      jazz: 0,
      classicRock: 0,
      rap: 4,
      indie: 0,
      rnb: 0,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 0,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 5,
      house : 1,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Peacoat - Future',
      art: 'Song-Covers/Trap/peacoat.jpeg',
      sample: 'Song-Samples/Trap/Future - Peacoat (Audio).mp3',
      pop: 0,
      jazz: 0,
      classicRock: 0,
      rap: 4,
      indie: 0,
      rnb: 1,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 1,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 5,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    {
      name: 'Jane - Migos',
      art: 'Song-Covers/Trap/jane.jpeg',
      sample: 'Song-Samples/Trap/Migos - Jane (Official Audio).mp3',
      pop: 0,
      jazz: 1,
      classicRock: 0,
      rap: 4,
      indie: 0,
      rnb: 0,
      metal: 0,
      blues: 0,
      folk: 0,
      soul: 1,
      country: 0,
      classical: 0,
      latin: 0,
      reggae: 0,
      funk: 0,
      altRock: 0,
      trap: 5,
      house : 0,
      neoSoul: 0,
      score: 0,
    },
    genre = 'trap'
  ]
};

const scoreTally = {
  pop: 0,
  jazz: 0,
  classicRock: 0,
  rap: 0,
  indie: 0,
  rnb: 0,
  metal: 0,
  blues: 0,
  folk: 0,
  soul: 0,
  country: 0,
  classical: 0,
  latin: 0,
  reggae: 0,
  funk: 0,
  altRock: 0,
  trap: 0,
  house : 0,
  neoSoul: 0,
}
